apiVersion: v1
kind: Service
metadata:
  name: reservation
spec:
  selector:
    app: reservation
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reservation-app
  template:
    metadata:
      labels:
        app: reservation-app
    spec:
      containers:
      - image: reservation-image:latest
        name: containerReservation
        imagePullPolicy: IfNotPresent