apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: api
type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: api-image:latest
        name: containerApi
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always